Planos para o jantar
Neste desafio você vai encontrar um erro de sintaxe e vai corrigi-lo. Um erro de sintaxe frequentemente consiste em caracteres incorretos ou ausentes.

Abebi deseja imprimir que refeição vai preparar para o jantar para saber o que comprar no supermercado. Mas ela vê undefined em vez de curry.

INSTRUÇÕES
Encontre e corrija o erro de sintaxe neste código.

Verifique o uso correto de maiúsculas e a grafia
Substitua o código incorreto pelo código correto

let meals = {
  monday: 'curry',
  tuesday: 'soup',
  wednesday: 'rice',
  ___: ___
};
let dinner = 'Dinner for Monday: ' + meals.monday;
console.log(dinner);
___
