Maçãs aritméticas
Neste desafio você vai ver um erro aritmético. Erros aritméticos acontecem quando alto está errado com a parte matemática do código.

O chef instrutor Demitri quer saber quantas maçãs ele precisará para a sua aula de culinária.

INSTRUÇÕES
Demitri fez a função multiplyApples() para obter três maçãs para cada aluno. Mas a função retorna um número que parece errado.

Encontre o erro aritmético na declaração de função multiplyApples()

Edite a função multiplyApples() para que o resultado dê a cada um dos 12 students três maçãs

function multiplyApples(students, ___) {
  return students * 3edit;
};
console.log(multiplyApples(12));
