Registro de ingredientes
Neste desafio, você vai usar console.log() para depurar um erro de lógica em um laço for clássico. console.log() é uma ferramenta útil que pode mostrar o que está acontecendo dentro das funções ou laços.

INSTRUÇÕES
Algo está errado com a aritmética da função showList().

Experimente mudar o retorno para um console.log() para ver o que está acontecendo na função.

Mude o valor de i no laço for para ver todos os ingredientes.


let ingredientsList = [
  'flour',
  'salt',
  'milk',
  'eggs',
  'baking powder',
  'sugar',
  ___
];
function showList(list, ___) {
  for (let i = 0edit; i < list.length; i++) {
    return console.log(list[i]);
  }
};
showList(ingredientsList);


